name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: DzHjaBMPRs5MdmEA7540OC5D
  VERCEL_PROJECT_ID: prj_DSVkNMKi6cYIa7R1sLN6UGe6ggGb
on:
  workflow_dispatch:
  push:
    branches:
      - test
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=gqCFCn2cINElNYH8GKHSm4Pc

      - name: Build Project Artifacts
        run: vercel build --token=gqCFCn2cINElNYH8GKHSm4Pc

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=gqCFCn2cINElNYH8GKHSm4Pc
